# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

config.bind('gt', 'tab-next')
config.bind('gT', 'tab-prev')
config.bind('x', 'tab-close')

c.aliases['r'] = 'open'
