#! /bin/sh

sxhkd -m -1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         6
bspc config window_gap          12

bspc config normal_border_color "#005555"
bspc config focused_border_color "#00FFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

lemonbar_input 2>/dev/null | lemonbar -p
volume_set.sh 50%
